include:
  - project: 'renovate-bot/renovate-runner'
    file: '/templates/renovate.gitlab-ci.yml'
    ref: v3.18.3
  - template: 'Workflows/Branch-Pipelines.gitlab-ci.yml'

variables:
  LOG_LEVEL: info
  RENOVATE_LOG_FILE_LEVEL: trace
  RENOVATE_EXTENDS: ""
  RENOVATE_CONFIG_FILE: "config-default.js"
  RENOVATE_REQUIRE_CONFIG: "false"
  RENOVATE_AUTODISCOVER: "true"
  RENOVATE_AUTODISCOVER_FILTER: "${CI_PROJECT_ROOT_NAMESPACE}/renovate"
  RENOVATE_DRY_RUN: "false"
  RENOVATE_BASE_BRANCHES: "${CI_COMMIT_REF_NAME}"
  RENOVATE_BRANCH_PREFIX: "renovate-groupall-pinned/"

renovate:
  rules:
   - when: manual

renovate-default:
  variables:
    RENOVATE_EXTENDS: "gitlab>${CI_PROJECT_PATH}//config-presets/default"
  extends:
    - renovate

renovate-groupall:
  variables:
    RENOVATE_EXTENDS: "gitlab>${CI_PROJECT_PATH}//config-presets/groupall"
  extends:
    - renovate

